services:
  nats-agent:
    pull_policy: always
    restart: unless-stopped

  ai-processor:
    pull_policy: always
    restart: unless-stopped

  dcgm-exporter:
    restart: unless-stopped

  node-exporter:
    restart: unless-stopped
