{
 "title": "Serverless GPU Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Queue Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stream message count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(stream_name) (jetstream_stream_total_messages{server_id=\"http://nats:8222\"})",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Pending messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(consumer_name) (jetstream_consumer_num_pending{server_id=~\"http://nats:8222\", stream_name=~\"GPU_JOBS\", consumer_name=~\"gpu-workers\"})",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Acks Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jetstream_consumer_num_ack_pending{server_id=~\"http://nats:8222\", stream_name=~\"GPU_JOBS\", consumer_name=~\"gpu-workers\"}) by(consumer_name) ",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "description": "Includes Orchestrator and gpu workers",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gnatsd_varz_connections)" }
   ]
  },
  { "title": "Orchestrator Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Node Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orchestrator_node_count" }
   ]
  },
  {
   "title": "Provisioning Node Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_node_count_by_state{state=\"provisioning\"}"
    }
   ]
  },
  {
   "title": "Ready Node Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_node_count_by_state{state=\"ready\"}"
    }
   ]
  },
  {
   "title": "Node Count by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "orchestrator_node_count_by_state",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}